name: rick_test
description: "no description"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_svg: ^2.0.17
  auto_size_text: ^3.0.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.3
  internet_connection_checker: ^3.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/assets/images/Rick_and_Morty.svg